# Generated by Django 5.1.5 on 2025-02-10 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='nome', max_length=15),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='cognome', max_length=15),
        ),
        migrations.AddField(
            model_name='subjectdata',
            name='grade',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='subjectdata',
            name='leaves',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subjectdata',
            name='name',
            field=models.CharField(default='materia', max_length=15),
        ),
        migrations.AddField(
            model_name='subjectdata',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='voti.student'),
        ),
    ]
